{
 "title": "Pool Overview",
 "time": { "from": "1969-12-31T23:00:00.000Z", "to": "1970-01-01T00:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "lapis",
    "label": "Simulation Run",
    "query": "SHOW TAG VALUES WITH KEY = \"tardis\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Claimed slots",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "drone_status_caching",
     "select": [
      [
       { "params": [ "claimed_slots" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tardis", "operator": "=~", "value": "/^$lapis$/" }
     ]
    }
   ]
  },
  {
   "title": "Free slots",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "drone_status_caching",
     "select": [
      [
       { "params": [ "free_slots" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tardis", "operator": "=~", "value": "/^$lapis$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_pool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "resource_status",
     "select": [
      [
       { "params": [ "requested_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "tardis", "operator": "=~", "value": "/^$lapis$/" }
     ]
    }
   ]
  },
  {
   "title": "Ratio of slots with caching jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}